brew "ghq"
brew "gibo"
brew "hub"
brew "mackup"
brew "peco"
brew "spin"
brew "the_silver_searcher"
brew "tig"
brew "tmux"
brew "tree"

tap "hoddy3190/my-tap"
brew "libo"

cask_args appdir: "/Applications"
tap "homebrew/cask"
cask "alfred"
cask "android-studio"
cask "docker"
cask "google-chrome"
cask "google-japanese-ime"
cask "intellij-idea"
cask "iterm2"
cask "karabiner-elements"
cask "kobo"
cask "pycharm-ce"
cask "slack"
cask "visual-studio-code"
